# Generated by Django 4.2.27 on 2026-02-13 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, help_text='Unique member identifier', max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('trainee', 'Trainee'), ('instructor', 'Instructor'), ('admin', 'Administrator')], default='trainee', max_length=20)),
                ('position', models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Chaplain', 'Chaplain'), ('Parliamentarian', 'Parliamentarian'), ('General Member', 'General Member')], default='General Member', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
