# Generated by Django 4.2.27 on 2026-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inactivity_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
