# Generated by Django 4.2.27 on 2026-03-12 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_inactivity_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('in_progress', 'In Progress'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.CharField(blank=True, help_text='Unique login/member identifier, e.g. N12345678', max_length=20, null=True, unique=True),
        ),
    ]
