# Generated by Django 4.2.27 on 2026-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_course_options_course_code_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
