# Generated by Django 4.2.27 on 2026-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_course_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_member_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='selected_roles',
            field=models.JSONField(default=list),
        ),
    ]
