# Generated by Django 4.2.27 on 2026-04-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_course_assigned_member_ids_course_selected_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assigned_member_ids',
        ),
        migrations.RemoveField(
            model_name='course',
            name='selected_roles',
        ),
    ]
