# Generated by Django 4.2.27 on 2026-04-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('assigned', 'Course Assigned'), ('due_soon', 'Due Soon'), ('due_today', 'Due Today'), ('warning', 'Warning'), ('success', 'Success'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('general', 'General Message')], default='info', max_length=20),
        ),
    ]
