# Generated by Django 4.2.27 on 2026-03-26 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_course_options_course_code_course_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('pdf', 'PDF'), ('external_video', 'External Video'), ('quiz', 'Quiz'), ('text', 'Text Content'), ('link', 'Link')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_items/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('text_content', models.TextField(blank=True, default='')),
                ('quiz_data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('audience_type', models.CharField(choices=[('all', 'All'), ('role', 'Role'), ('member', 'Member')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.module')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='training.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ItemPositionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Chaplain', 'Chaplain'), ('Parliamentarian', 'Parliamentarian'), ('General Member', 'General Member')], max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_targets', to='training.item')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('item', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ItemMemberAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_targets', to='training.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_member_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CoursePositionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Chaplain', 'Chaplain'), ('Parliamentarian', 'Parliamentarian'), ('General Member', 'General Member')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_targets', to='accounts.course')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('course', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CourseMemberAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_targets', to='accounts.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_member_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
