# Generated by Django 4.2.27 on 2026-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('external_video', 'External Video'), ('quiz', 'Quiz'), ('text', 'Text Content'), ('link', 'Link')], max_length=30),
        ),
    ]
