# Generated by Django 4.2.27 on 2026-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
