# Generated by Django 4.2.27 on 2026-03-08 02:21
# Automatically handles creating the Training Structure in the database file when Migrations run

from django.db import migrations

def create_training_data(apps, schema_editor):
    Track = apps.get_model('training', 'Track')
    Module = apps.get_model('training', 'Module')

    track = Track.objects.create(name="Leadership Track")

    Module.objects.create(
        track=track,
        title="Leadership Foundations",
        order=1,
        required=True,
    )

    Module.objects.create(
        track=track,
        title="Team Communication",
        order=2,
        required=True,
    )

    Module.objects.create(
        track=track,
        title="Conflict Resolution",
        order=3,
        required=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_training_data),
    ]