# Generated by Django 4.2.27 on 2026-04-08 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_item_due_date_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
