# Generated by Django 4.2.27 on 2026-04-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_module_instructor_module_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
    ]
