# Generated by Django 4.2.27 on 2026-03-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_moduleprogress_last_activity'),
        ('training', '0003_seed_training_data'),
    ]

    operations = [
    ]
