# Generated by Django 4.2.27 on 2026-03-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
