# Generated by Django 4.2.27 on 2026-04-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_quizattempt_short_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending_review', 'Pending Review')], default='not_started', max_length=20),
        ),
    ]
